# This file is maintained in https://github.com/WeblateOrg/meta/
# Configuration for https://kodiakhq.com/
version = 1

[merge]
method = "rebase_fast_forward"

[update]
ignored_usernames = ["dependabot", "weblate"]
